### ISSUE TITLE
Function get_worldclim_prectemp is not found. 

### ISSUE THREAD

**Issue by rockahominy** [RemkoDuursma/speciesmap#11]
Has function get_worldclim_prectemp been removed from speciesmap? An error "Error: could not find function "get_worldclim_prectemp" is returned when running the function.

**Comment by RemkoDuursma** [comment]
Yes at some point I restructured the package to make it a bit more general. Take a look at `get_climate_vars` and also the vignette on https://remkoduursma.github.io/speciesmap/.
