### ISSUE TITLE
speciesmap had non-zero exit status

### ISSUE THREAD

**Issue by PabloCSZ** [RemkoDuursma/speciesmap#12]
Hi, 

I tried to install your package to download PET data from the CGIAR-CSI web page but I got a message indicating the installation is not possible. 

Error: Failed to install 'speciesmap' from GitHub:
  (convertido del aviso) installation of package ‘E:/Win Temporal files/..../speciesmap_0.4-4.tar.gz’ had non-zero exit status

I looked the error online and it seems your package is no longer a valid R package.... I am not quite sure if this is a problem in my computer or in the code.

**Comment by RemkoDuursma** [comment]
Thanks - I will take a look

**Comment by RemkoDuursma** [comment]
It installs fine here - I think the problem arises because you are installing from a path with a space in it.
